# Generated by Django 5.0.2 on 2024-02-24 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.CharField(max_length=255, verbose_name="カテゴリ"),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(verbose_name="質問文"),
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="選択肢")),
                ("score", models.IntegerField(verbose_name="スコア")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="myapp.question",
                    ),
                ),
            ],
        ),
    ]
